### ISSUE TITLE
Menu select adjustments

### ISSUE THREAD

**Issue by tewshi** [rotki/ui-library-compat#173]
## Description

after integrating with the app, some things need to be adjusted.

## Tasks

- [x] make the height match with what we have on the design
- [x] allow custom height for the activator and the menu items (ensure scrolling works smoothly)
- [x] top border is missing for outlined variant when there is a value
- [x] add focus outline/background highlight
- [x] add readonly state to the activator
- [x] prevent layout jumps when the activator is focused
- [x] prevent layout jumps for floating label variant when un/focusing
- [x] focus on the activator after selection
